const posts = [{
        _id:'1',
        img: '',
        title: 'html',
        rawContent: '{}',
        htmlContent: '',
        describe: 'html复习',
        likes: '',
        views: '',
        tags: '',
        category: 'learn',
        createTime: Date.now,
        updateTime: Date.now,
    },
    {
        _id:'2',
        img: '',
        title: 'css',
        rawContent: '{}',
        htmlContent: '',
        describe: 'css复习',
        likes: '',
        views: '',
        tags: '',
        category: 'learn',
        createTime: Date.now,
        updateTime: Date.now,
    },
    {
        _id:'3',
        img: '',
        title: 'javascript',
        rawContent: '{}',
        htmlContent: '',
        describe: 'javascript复习',
        likes: '',
        views: '',
        tags: '',
        category: 'learn',
        createTime: Date.now,
        updateTime: Date.now,
    },
    {
        _id:'4',
        img: '',
        title: 'vue',
        rawContent: '{}',
        htmlContent: '',
        describe: 'vue复习',
        likes: '',
        views: '',
        tags: '',
        category: 'learn',
        createTime: Date.now,
        updateTime: Date.now,
    },
    {
        _id:'5',
        img: '',
        title: 'react',
        rawContent: '{}',
        htmlContent: '',
        describe: 'react复习',
        likes: '',
        views: '',
        tags: '',
        category: 'learn',
        createTime: Date.now,
        updateTime: Date.now,
    },
]

module.exports=posts